sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGiNty7LM4iz8gQRCmF
    access-key-secret: 8wzgFlcdIaGmXiSw7mM0M8aa7FJ2px
    bucket-name: web-ymy-spring
  redis: localhost
  port: 6379
  #password: 123456
  database: 10
  timeout: 100000
