sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint:
    access-key-id:
    access-key-secret: 
    bucket-name: 
  redis: localhost
  port: 6379
  #password: 123456
  database: 10
  timeout: 100000

  wechat:
    appid: wx9e78aad242a81540
    secret: b47d1ba5203527e1b77ca2df4d4bb076
